/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#81e7c3",
        "secondary": "#00684f",
        "tertiary-fixed-dim": "#8cd3f0",
        "on-secondary-container": "#005d47",
        "on-tertiary-fixed": "#003d4f",
        "tertiary": "#04647d",
        "on-secondary": "#c6ffe7",
        "background": "#f8f6f2",
        "surface-container-low": "#f2f1ec",
        "surface-variant": "#deddd8",
        "error-dim": "#b92902",
        "surface-container": "#e9e8e4",
        "surface-bright": "#f8f6f2",
        "secondary-dim": "#005b45",
        "on-error-container": "#520c00",
        "surface": "#f8f6f2",
        "on-tertiary-container": "#005267",
        "on-primary-fixed": "#000000",
        "inverse-primary": "#ff5357",
        "surface-container-lowest": "#ffffff",
        "tertiary-dim": "#00576e",
        "outline": "#777774",
        "primary-fixed": "#ff7574",
        "surface-tint": "#ba0023",
        "on-primary-fixed-variant": "#60000d",
        "inverse-surface": "#0e0e0d",
        "primary-dim": "#a3001d",
        "error-container": "#f95630",
        "tertiary-container": "#9ae1ff",
        "on-error": "#ffefec",
        "surface-container-high": "#e4e2de",
        "secondary-fixed": "#8ff6d0",
        "secondary-container": "#8ff6d0",
        "outline-variant": "#aeadaa",
        "on-primary": "#ffefee",
        "primary-container": "#ff7574",
        "error": "#b02500",
        "primary": "#ba0023",
        "tertiary-fixed": "#9ae1ff",
        "surface-container-highest": "#deddd8",
        "on-tertiary-fixed-variant": "#005c74",
        "primary-fixed-dim": "#ff595c",
        "on-secondary-fixed": "#004936",
        "inverse-on-surface": "#9e9d99",
        "on-primary-container": "#4e0008",
        "surface-dim": "#d5d4d0",
        "on-background": "#2e2f2d",
        "on-surface": "#2e2f2d",
        "on-surface-variant": "#5b5c59",
        "on-secondary-fixed-variant": "#00684f",
        "on-tertiary": "#e3f6ff"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Be Vietnam Pro"],
        "label": ["Plus Jakarta Sans"]
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
};
